package com.sweng894.GetVaccinated.api.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.sweng894.GetVaccinated.api.entity.Company;
import lombok.*;

import java.util.ArrayList;
import java.util.Date;
@Data
@ToString
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "vaccine")
public class Vaccine {
  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  private String id;
  @DynamoDBAttribute
  private Company company;
  @DynamoDBAttribute
  private String title;
  @DynamoDBAttribute
  private Date launchDate;
  @DynamoDBAttribute
  private int noOfShots;
  @DynamoDBAttribute
  private String distributionProcess;
  @DynamoDBAttribute
  private ArrayList<VaccineLocation> locations;
}
