package com.sweng894.GetVaccinated.api.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.Date;

@DynamoDBTable(tableName = "Vaccine")
public class Vaccine {
  private int id;
  private int companyId;
  private String title;
  private Date launchDate;
  private int noOfShots;
  private String distributionProcess;

  public Vaccine() { }

  public Vaccine(int id, int companyId, String title, Date launchDate) {
    this.id = id;
    this.companyId = companyId;
    this.title = title;
    this.launchDate = launchDate;
  }

  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  public int getId() {
    return id;
  }

  public void setId(int id) {
    this.id = id;
  }

  @DynamoDBAttribute
  public int getCompanyId() {
    return companyId;
  }

  public void setCompanyId(int companyId) {
    this.companyId = companyId;
  }

  @DynamoDBAttribute
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  @DynamoDBAttribute
  public Date getLaunchDate() {
    return launchDate;
  }

  public void setLaunchDate(Date launchDate) {
    this.launchDate = launchDate;
  }

  @DynamoDBAttribute
  public int getNoOfShots() {
    return noOfShots;
  }

  public void setNoOfShots(int noOfShots) {
    this.noOfShots = noOfShots;
  }

  @DynamoDBAttribute
  public String getDistributionProcess() {
    return distributionProcess;
  }

  public void setDistributionProcess(String distributionProcess) {
    this.distributionProcess = distributionProcess;
  }
}
